"""Initial schema — all tables as of v1.0

Revision ID: 0001
Revises:
Create Date: 2025-01-01 00:00:00.000000

This migration creates all tables that are currently managed via
SQLAlchemy's create_all() on startup.  Future changes should use
incremental revisions generated by `alembic revision --autogenerate`.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── users ──────────────────────────────────────────────────────────────
    op.create_table(
        'users',
        sa.Column('id',                   sa.Integer(),    primary_key=True),
        sa.Column('email',                sa.String(),     nullable=False, unique=True),
        sa.Column('name',                 sa.String(),     nullable=True),
        sa.Column('hashed_password',      sa.String(),     nullable=False),
        sa.Column('study_hours_per_day',  sa.Float(),      nullable=True),
        sa.Column('learning_goal',        sa.String(),     nullable=True),
        sa.Column('profile_cluster',      sa.Integer(),    nullable=True),
        sa.Column('created_at',           sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    # ── user_profiles ──────────────────────────────────────────────────────
    op.create_table(
        'user_profiles',
        sa.Column('id',            sa.Integer(),  primary_key=True),
        sa.Column('user_id',       sa.Integer(),  sa.ForeignKey('users.id'), nullable=True),
        sa.Column('profile_label', sa.String(),   nullable=True),
        sa.Column('features',      sa.JSON(),     nullable=True),
        sa.Column('updated_at',    sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'])
    op.create_index('ix_user_profiles_profile_label', 'user_profiles', ['profile_label'])

    # ── agent_decisions ────────────────────────────────────────────────────
    op.create_table(
        'agent_decisions',
        sa.Column('id',               sa.Integer(),  primary_key=True),
        sa.Column('agent_name',       sa.String(),   nullable=True),
        sa.Column('user_id',          sa.Integer(),  sa.ForeignKey('users.id'), nullable=True),
        sa.Column('input_features',   sa.JSON(),     nullable=True),
        sa.Column('output_decision',  sa.JSON(),     nullable=True),
        sa.Column('timestamp',        sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('event_id',         sa.String(),   nullable=True),
    )
    op.create_index('ix_agent_decisions_agent_name', 'agent_decisions', ['agent_name'])
    op.create_index('ix_agent_decisions_user_id',    'agent_decisions', ['user_id'])
    op.create_index('ix_agent_decisions_timestamp',  'agent_decisions', ['timestamp'])
    op.create_index('ix_agent_decisions_event_id',   'agent_decisions', ['event_id'])

    # ── study_plans ────────────────────────────────────────────────────────
    op.create_table(
        'study_plans',
        sa.Column('id',                    sa.Integer(),  primary_key=True),
        sa.Column('user_id',               sa.Integer(),  sa.ForeignKey('users.id'), nullable=True),
        sa.Column('plan_json',             sa.JSON(),     nullable=True),
        sa.Column('generated_by_agent_id', sa.Integer(),  sa.ForeignKey('agent_decisions.id'), nullable=True),
        sa.Column('valid_from',            sa.DateTime(), nullable=True),
        sa.Column('valid_to',              sa.DateTime(), nullable=True),
        sa.Column('created_at',            sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_study_plans_user_id', 'study_plans', ['user_id'])

    # ── progress_logs ──────────────────────────────────────────────────────
    op.create_table(
        'progress_logs',
        sa.Column('id',                 sa.Integer(), primary_key=True),
        sa.Column('user_id',            sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('academic_metric',    sa.Float(),   nullable=True),
        sa.Column('attendance',         sa.Float(),   nullable=True),
        sa.Column('study_time',         sa.Float(),   nullable=True),
        sa.Column('timestamp',          sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('logged_by_agent_id', sa.Integer(), sa.ForeignKey('agent_decisions.id'), nullable=True),
    )
    op.create_index('ix_progress_logs_user_id',   'progress_logs', ['user_id'])
    op.create_index('ix_progress_logs_timestamp', 'progress_logs', ['timestamp'])

    # ── stress_logs ────────────────────────────────────────────────────────
    op.create_table(
        'stress_logs',
        sa.Column('id',                 sa.Integer(), primary_key=True),
        sa.Column('user_id',            sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('stress_level',       sa.Float(),   nullable=True),
        sa.Column('sleep_hours',        sa.Float(),   nullable=True),
        sa.Column('physical_activity',  sa.Float(),   nullable=True),
        sa.Column('timestamp',          sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('logged_by_agent_id', sa.Integer(), sa.ForeignKey('agent_decisions.id'), nullable=True),
    )
    op.create_index('ix_stress_logs_user_id',   'stress_logs', ['user_id'])
    op.create_index('ix_stress_logs_timestamp', 'stress_logs', ['timestamp'])

    # ── motivation_logs ────────────────────────────────────────────────────
    op.create_table(
        'motivation_logs',
        sa.Column('id',                 sa.Integer(), primary_key=True),
        sa.Column('user_id',            sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('motivation_score',   sa.Float(),   nullable=True),
        sa.Column('category',           sa.String(),  nullable=True),
        sa.Column('intervention',       sa.String(),  nullable=True),
        sa.Column('timestamp',          sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('logged_by_agent_id', sa.Integer(), sa.ForeignKey('agent_decisions.id'), nullable=True),
    )
    op.create_index('ix_motivation_logs_user_id',   'motivation_logs', ['user_id'])
    op.create_index('ix_motivation_logs_timestamp', 'motivation_logs', ['timestamp'])

    # ── group_data ─────────────────────────────────────────────────────────
    op.create_table(
        'group_data',
        sa.Column('id',             sa.Integer(), primary_key=True),
        sa.Column('group_label',    sa.String(),  nullable=True),
        sa.Column('group_features', sa.JSON(),    nullable=True),
        sa.Column('created_at',     sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_group_data_group_label', 'group_data', ['group_label'])

    # ── group_membership ───────────────────────────────────────────────────
    op.create_table(
        'group_membership',
        sa.Column('id',        sa.Integer(), primary_key=True),
        sa.Column('group_id',  sa.Integer(), sa.ForeignKey('group_data.id'), nullable=True),
        sa.Column('user_id',   sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_group_membership_group_id', 'group_membership', ['group_id'])
    op.create_index('ix_group_membership_user_id',  'group_membership', ['user_id'])

    # ── model_predictions ──────────────────────────────────────────────────
    op.create_table(
        'model_predictions',
        sa.Column('id',            sa.Integer(), primary_key=True),
        sa.Column('agent_name',    sa.String(),  nullable=True),
        sa.Column('user_id',       sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('prediction',    sa.JSON(),    nullable=True),
        sa.Column('model_version', sa.String(),  nullable=True),
        sa.Column('timestamp',     sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_model_predictions_agent_name', 'model_predictions', ['agent_name'])
    op.create_index('ix_model_predictions_user_id',    'model_predictions', ['user_id'])
    op.create_index('ix_model_predictions_timestamp',  'model_predictions', ['timestamp'])

    # ── schedule_history ───────────────────────────────────────────────────
    op.create_table(
        'schedule_history',
        sa.Column('id',                   sa.Integer(), primary_key=True),
        sa.Column('user_id',              sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('old_plan_id',          sa.Integer(), sa.ForeignKey('study_plans.id'), nullable=True),
        sa.Column('new_plan_id',          sa.Integer(), sa.ForeignKey('study_plans.id'), nullable=True),
        sa.Column('reason',               sa.String(),  nullable=True),
        sa.Column('changed_by_agent_id',  sa.Integer(), sa.ForeignKey('agent_decisions.id'), nullable=True),
        sa.Column('timestamp',            sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_schedule_history_user_id',   'schedule_history', ['user_id'])
    op.create_index('ix_schedule_history_timestamp', 'schedule_history', ['timestamp'])

    # ── syllabus_documents ─────────────────────────────────────────────────
    op.create_table(
        'syllabus_documents',
        sa.Column('id',                sa.Integer(), primary_key=True),
        sa.Column('kind',              sa.String(),  nullable=True),
        sa.Column('subject',           sa.String(),  nullable=True),
        sa.Column('original_filename', sa.String(),  nullable=True),
        sa.Column('stored_path',       sa.String(),  nullable=True),
        sa.Column('topics',            sa.JSON(),    nullable=True),
        sa.Column('metadata_json',     sa.JSON(),    nullable=True),
        sa.Column('created_at',        sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_syllabus_documents_kind',    'syllabus_documents', ['kind'])
    op.create_index('ix_syllabus_documents_created_at', 'syllabus_documents', ['created_at'])

    # ── study_materials ────────────────────────────────────────────────────
    op.create_table(
        'study_materials',
        sa.Column('id',          sa.Integer(), primary_key=True),
        sa.Column('user_id',     sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('subject',     sa.String(),  nullable=True),
        sa.Column('filename',    sa.String(),  nullable=True),
        sa.Column('stored_path', sa.String(),  nullable=True),
        sa.Column('kind',        sa.String(),  nullable=True, default='material'),
        sa.Column('topics',      sa.JSON(),    nullable=True),
        sa.Column('file_size',   sa.Integer(), nullable=True),
        sa.Column('created_at',  sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_study_materials_user_id',    'study_materials', ['user_id'])
    op.create_index('ix_study_materials_subject',    'study_materials', ['subject'])
    op.create_index('ix_study_materials_created_at', 'study_materials', ['created_at'])

    # ── community_posts ────────────────────────────────────────────────────
    op.create_table(
        'community_posts',
        sa.Column('id',           sa.Integer(), primary_key=True),
        sa.Column('group_id',     sa.Integer(), nullable=True),
        sa.Column('user_id',      sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('author_name',  sa.String(),  nullable=True),
        sa.Column('content',      sa.String(),  nullable=False),
        sa.Column('tag',          sa.String(),  nullable=True),
        sa.Column('likes',        sa.Integer(), nullable=True, server_default='0'),
        sa.Column('created_at',   sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_community_posts_group_id',   'community_posts', ['group_id'])
    op.create_index('ix_community_posts_user_id',    'community_posts', ['user_id'])
    op.create_index('ix_community_posts_created_at', 'community_posts', ['created_at'])

    # ── community_comments ─────────────────────────────────────────────────
    op.create_table(
        'community_comments',
        sa.Column('id',           sa.Integer(), primary_key=True),
        sa.Column('post_id',      sa.Integer(), sa.ForeignKey('community_posts.id'), nullable=True),
        sa.Column('user_id',      sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('author_name',  sa.String(),  nullable=True),
        sa.Column('content',      sa.String(),  nullable=False),
        sa.Column('created_at',   sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_community_comments_post_id',    'community_comments', ['post_id'])
    op.create_index('ix_community_comments_user_id',    'community_comments', ['user_id'])
    op.create_index('ix_community_comments_created_at', 'community_comments', ['created_at'])

    # ── document_chunks ────────────────────────────────────────────────────
    op.create_table(
        'document_chunks',
        sa.Column('id',           sa.Integer(),  primary_key=True),
        sa.Column('user_id',      sa.Integer(),  sa.ForeignKey('users.id'), nullable=True),
        sa.Column('material_id',  sa.Integer(),
                  sa.ForeignKey('study_materials.id', ondelete='CASCADE'), nullable=True),
        sa.Column('subject',      sa.String(),   nullable=True),
        sa.Column('filename',     sa.String(),   nullable=True),
        sa.Column('chunk_index',  sa.Integer(),  nullable=False, server_default='0'),
        sa.Column('content',      sa.Text(),     nullable=False),
        sa.Column('embedding',    sa.JSON(),     nullable=True),
        sa.Column('created_at',   sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_document_chunks_user_id',     'document_chunks', ['user_id'])
    op.create_index('ix_document_chunks_material_id', 'document_chunks', ['material_id'])


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_table('document_chunks')
    op.drop_table('community_comments')
    op.drop_table('community_posts')
    op.drop_table('study_materials')
    op.drop_table('syllabus_documents')
    op.drop_table('schedule_history')
    op.drop_table('model_predictions')
    op.drop_table('group_membership')
    op.drop_table('group_data')
    op.drop_table('motivation_logs')
    op.drop_table('stress_logs')
    op.drop_table('progress_logs')
    op.drop_table('study_plans')
    op.drop_table('agent_decisions')
    op.drop_table('user_profiles')
    op.drop_table('users')
